### ISSUE TITLE
TypeError: undefined is not a function when testing with PhantomJs

### ISSUE THREAD

**Issue by angelomachado** [alphasights/ember-scrollable#27]
Release [0.0.3](https://github.com/alphasights/ember-scrollable/compare/0.3.3...master#diff-499447ac5ce8a7c1077b7503f9403d0dR206) introduces the new ES6 Number feature which breaks PhantomJS. I think it is a good idea to keep the globals parseInt and isNaN until Number is oficially supported.

**Comment by buschtoens** [comment]
Apparently `ember-cli-babel` [doesn't include the polyfill by default](https://github.com/babel/ember-cli-babel#polyfill) (anymore ?).

I'm for adding these lines to the top of the file:

```js
Number.parseInt = Number.parseInt || parseInt;
Number.isNaN = Number.isNaN || isNaN;
```

This way we don't need to make the parent app include an unnecessarily bloated polyfill while also staying ES6 compliant.

**Comment by offirgolan** [comment]
Closing this issue as all CI testing is now done on Chrome.
