### ISSUE TITLE
[BUG] Width detection incorrect in FF

### ISSUE THREAD

**Issue by offirgolan** [alphasights/ember-scrollable#34]
It seems like the width for the `tse-scrollable-content` div is incorrectly set in the following env:

OSX version: 10.12 (16A323)
FireFox: 48 and 50.1.0
URL: http://offirgolan.github.io/ember-light-table/#/grouped

### Chrome 55

<img width="1440" alt="screen shot 2017-01-04 at 9 58 01 pm" src="https://cloud.githubusercontent.com/assets/575938/21670432/e6b7b94c-d2c8-11e6-8461-b284f0cb4deb.png">

### Firefox 50.1.0

<img width="1440" alt="screen shot 2017-01-04 at 9 55 29 pm" src="https://cloud.githubusercontent.com/assets/575938/21670397/92c4f5b6-d2c8-11e6-8f73-a05e803aeb3f.png">

As you can see, this is screwing up the table's alignment. 

![81cba1b0-d269-11e6-8d38-1a500766278c](https://cloud.githubusercontent.com/assets/575938/21670551/dcc1dc6e-d2c9-11e6-9915-88c862b3a5df.png)

cc @taras

**Comment by offirgolan** [comment]
Update:

I believe this is happening because of the following block:

https://github.com/alphasights/ember-scrollable/blob/master/addon/components/ember-scrollable.js#L87-L89

The correct width of the content area should be `996px` + the forced `17px` for the scrollbar adds up to the `1013px` in FF.

**Comment by offirgolan** [comment]
Update 2:

Why is this above block needed if we are forcing the scrollbar have a fixed position? Is that block of code just outdated (looks like it was written for chrome v25)?

```css
.tse-scrollbar {
  position : absolute;
  z-index : 99;
  top : 0;
  right : 0;
  bottom : 0;
  width : 11px;
}
```

**Comment by alexander-alvarez** [comment]
@offirgolan  from what I could deduce

```
the right sends the scrollbar area/handle to the right side of the content
 ------------------- _  top 0
|                   |x|
|                   |x|   width 11px
|                   |x|
 ------------------- _  bottom 0

```

**Comment by offirgolan** [comment]
@alexander-alvarez not sure I follow what you're saying here. My point for the first Update is that we dont need to be forcing a scrollbar width for FF since the scrollbar is absolute positioned on top of the content.

**Comment by alexander-alvarez** [comment]
ohh -- I was trying to explain update 2 -- i have no idea why update 1 exists.
