### ISSUE TITLE
Content doesn't appear in the page

### ISSUE THREAD

**Issue by celicoo** [alphasights/ember-scrollable#41]
I'm trying to use but the component tag is making the content disappear:

![screenshot from 2017-01-25 19-08-53](https://cloud.githubusercontent.com/assets/7903844/22309289/c803ddf4-e331-11e6-83c3-d7966f74fe06.png)

Code:

```
{{#ember-scrollable autoHide=false}}
  <p>Some content</p>
  <p>Some more content</p>
  <p>Some content</p>
  <p>Some more content</p>
  <p>Some content</p>
  <p>Some more content</p>
  <p>Some content</p>
  <p>Some more content</p>
  <p>Some content</p>
  <p>Some more content</p>
{{/ember-scrollable}}
```

**Comment by ckl1989** [comment]
What did you do to solve this?

**Comment by ckl1989** [comment]
Derp, you need to set the height of the scrollable!
