### ISSUE TITLE
DevTools failed to parse SourceMap: https://mydomain.com/assets/ember-scrollable.css.map

### ISSUE THREAD

**Issue by rstudner** [alphasights/ember-scrollable#43]
Anyone else seeing this on the regular in chrome?

**Comment by bob-hanson** [comment]
I have an issue with this particular .map file trying to load from the Rails root on my localhost when proxying the ember requests. 

Im not in production yet, but this may have the same problem you are facing.

**Comment by alexander-alvarez** [comment]
Closing due to stale-ness. Please reopen if the issue persists

**Comment by musaffa** [comment]
You can fix it by unchecking "Enable CSS source maps" in Chrome settings.
