### ISSUE TITLE
Shared states

### ISSUE THREAD

**Issue by buschtoens** [alphasights/ember-scrollable#46]
All instances of `{{ember-scrollable}}` appear to share state.

If I hover over one container, not only the scrollbar of this container fades in, but all other containers do the same. Also, when using `scrollTo`, all containers scroll to that position.

**Comment by buschtoens** [comment]
Correction: the synced scrolling was my bad. However, I still have both scrollbars fading in and out synchronously. Is this intended behavior?

**Comment by offirgolan** [comment]
> I still have both scrollbars fading in and out synchronously. Is this intended behavior?

@buschtoens I believe so. When you hover over a scrollable div, the scrollbars should fade in to show the user that they can scroll either horizontally, vertically, or both.

**Comment by buschtoens** [comment]
I think I wasn't wording it clearly enough. I mean in two separate scroll
containers.

**Comment by offirgolan** [comment]
@buschtoens oh... I dont think that is intended....
