### ISSUE TITLE
Event Listeners not removed

### ISSUE THREAD

**Issue by buschtoens** [alphasights/ember-scrollable#47]
In `ember-scrollable.js` you're registering three two event listeners on `document.body` and one on `window`. As far as I can see these event listeners aren't removed when the element is destroyed.

**Comment by offirgolan** [comment]
@buschtoens thank you for reporting this.

@alexander-alvarez I suggest using `$.on` as well as namespacing the event with the component's elementId`

```js
$.on(`click.${this.get('elementId')}`);
$.on(`mouseover.${this.get('elementId')}`);
$.of(`.${this.get('elementId')}`); // turns them all off
```

**Comment by alexander-alvarez** [comment]
https://github.com/rwjblue/ember-lifeline#addeventlistener ?

**Comment by offirgolan** [comment]
@alexander-alvarez LOL ok ok my bad, I totally forgot that you are using ember-lifeline...

**Comment by buschtoens** [comment]
Gosh, I'm stupid. Haha. 🙈
Sorry for the noise. Just stumbled upon these lines and completely forgot
about lifeline, too. Sorry!
