### ISSUE TITLE
Recalculate on viewport change

### ISSUE THREAD

**Issue by offirgolan** [alphasights/ember-scrollable#5]
Currently, the scrollbar is recalculated when the window is resized which works great but I believe that it should also be recalculated when the height/width of the viewport has changed.

Let me give you an example:

In my app I have a filter toggle which when clicked, expands out a div with some options. When that button is clicked again, it hides the previously opened div. On both click events, the viewport height has changed and the scrollbars have not updated, leaving an awkward empty whitespace. 

When I resize the screen, the scrollbar gets recalculated and all is fixed.

**Comment by taras** [comment]
I'm not sure if it's possible that track height of an element. I might be able to use this approach http://www.prevent-default.com/detect-size-change-of-elements-using-transitions/

**Comment by offirgolan** [comment]
@taras I was able to fix my issue by doing the following: offirgolan/ember-light-table#60
