### ISSUE TITLE
Activate TravisCI for this repo

### ISSUE THREAD

**Issue by taras** [alphasights/ember-scrollable#6]
@Arkham to hookup this repo to TravisCI, TravisCI requires admin permissions on the organization. I don't have that, so could you please activate this repo on TravisCI?

**Comment by Arkham** [comment]
hey @taras done that, also the test suite is running here too: https://circleci.com/gh/alphasights/ember-scrollable

**Comment by taras** [comment]
oooh... hmm... now, I'm not sure what to do. Running 2 feels like a waste of resources. I didn't know about CircleCI

**Comment by taras** [comment]
I just realized the badges are in the readme.

**Comment by taras** [comment]
Let's leave TravisCI cause it has integration with the repo. I'm not sure about CircleCI

**Comment by Arkham** [comment]
👍  :)
