### ISSUE TITLE
Horizontal scrolling isn't working

### ISSUE THREAD

**Issue by kauthon** [alphasights/ember-scrollable#71]
I spooled up a new ember project and everytime I copy your code from Demo.  It never works.  Any ideas? I'm trying to figure out the horizontal scroll only. Thanks in advance.
  
  
CODE:
{{#ember-scrollable horizontal=true}}
  <ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li>7</li>
    <li>8</li>
    <li>9</li>
    <li>10</li>
  </ul>
{{/ember-scrollable}}

**Comment by alexander-alvarez** [comment]
Is there horizontal overflow? The scrollbar only appears if there is is overflow

**Comment by kauthon** [comment]
I tried overoverflow-x visible and auto and lot's of other combinations.

`http://d.pr/i/QFuc ` Droplr link screenshot  





On Tue, Apr 11, 2017 1:29 PM, Alex Alvarez notifications@github.com  wrote:
Is there horizontal overflow? The scrollbar only appears if there is is overflow

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Kevin RamirezCo-founder + CIO | Chief Innovation Officerm:443.326.3359w:
www.factsumo.come:kevin@factsumo.com

**Comment by alexander-alvarez** [comment]
sorry you're having trouble -- I copied the styles from the repo into a twiddle and everything is working fine.
https://ember-twiddle.com/52b5ff8ef9a1ca3db713684cdfd4e5a2?openFiles=templates.application.hbs%2C

the parent wrapper needs a width, and the children of ember-scrollable needs to have a width that's greater than the width of the parent in order to show up. it looks like you're getting wrapping of your elements instead of continuing in a straight horizontal line

**Comment by kauthon** [comment]
Sweet, that twiddle's css worked for me. I'll break it down, figure how it
worked and then I'll make a blog post and share it with you/everyone.
Thanks.Kevin  





On Tue, Apr 11, 2017 5:47 PM, Alex Alvarez notifications@github.com  wrote:
sorry you're having trouble -- I copied the styles from the repo into a twiddle
and everything is working fine.
https://ember-twiddle.com/52b5ff8ef9a1ca3db713684cdfd4e5a2?openFiles=templates.application.hbs%2C

the parent wrapper needs a width, and the children of ember-scrollable needs to
have a width that's greater than the width of the parent in order to show up. it
looks like you're getting wrapping of your elements instead of continuing in a
straight horizontal line

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Kevin RamirezCo-founder + CIO | Chief Innovation Officerm:443.326.3359w:
www.factsumo.come:kevin@factsumo.com
