### ISSUE TITLE
Bug with double scroll

### ISSUE THREAD

**Issue by Kulja** [alphasights/ember-scrollable#72]
There is a bug when there are vertical and horizontal scrollers on the screen like you have in your "Double Scroll" demo (https://alphasights.github.io/ember-scrollable/).

To reproduce in your demo:
Move vertical scroll to the middle and then move horizontal scroll but with the mouse click and then drag left or right (actually, dragging left or light is not necessary, just the click on horizontal scroll is enough). After the click the content will move to the top while vertical scroll will stay in the middle.

Actually, if you try randomly clicking on scrollers, it just seems there are some weird issues that pop up.

**Comment by alexander-alvarez** [comment]
I'm not seeing this on my machine. What browser are you running?

**Comment by Kulja** [comment]
I tried on safari osx and on chrome win10. Both show this problem.

**Comment by kevlarr** [comment]
I'm replicating this something similar on OSX using both Safari & Chrome:

Scrolling vertical content to middle first (with mouse wheel) then scrolling horizontal (by click and drag) is fine, but the moment I try to scroll down with mouse wheel (only **down** is an issue), it jumps back up a ways and _then_ start scrolling down.

**Comment by kevlarr** [comment]
I'm replicating this or something similar on OSX using both Safari & Chrome:

Scrolling vertical content to middle first (with mouse wheel) then scrolling horizontal (by click and drag) is fine, but the moment I try to scroll down with mouse wheel (only **down** is an issue), it jumps back up a ways and _then_ start scrolling down.

**Comment by alexander-alvarez** [comment]
@kevlarr  thanks. I can reproduce this. will investigate

**Comment by Kulja** [comment]
Now it is working ok. I am not sure what changed.
