### ISSUE TITLE
Internet Explorer 11 JS Errors on Demo Page

### ISSUE THREAD

**Issue by RobIsHere** [alphasights/ember-scrollable#79]
It seems like IE11 doesn't have some methods like parseInt defined.

How much work would it be to get this running in IE11, too? Is it just some fixing here and there or do you rely on newer browsers in depth?

**Comment by alexander-alvarez** [comment]
There shouldn't be instances of it as we're doing this: https://github.com/alphasights/ember-scrollable/commit/2ede7853eec2e3a5de1ad16664cf220088d07aee . If you find something we've missed please let us know, but first make sure you're on latest

**Comment by RobIsHere** [comment]
It happened on your demo page that is linked here. Is that on latest?

(win10/ie11)

**Comment by alexander-alvarez** [comment]
Ember Inspector tells me it's running on `0.4.3`.
@offirgolan  do you have access to update the demo page?

**Comment by offirgolan** [comment]
Yeah I do. I'll make an update after the next patch.

**Comment by offirgolan** [comment]
Demo has been updated.
