### ISSUE TITLE
didRender is repeatedly called upon mouse move

### ISSUE THREAD

**Issue by buschtoens** [alphasights/ember-scrollable#82]
Originally reported in https://github.com/offirgolan/ember-light-table/issues/363.

Merely moving the mouse over an instance of `{{ember-scrollable}}` is enough to constantly trigger `didRender`.

**Comment by buschtoens** [comment]
Disablling `updateMouseOffset` fixes this problem. My guess is that even though `horizontalMouseOffset` and `verticalMouseOffset` are not visibly rendered, nor do they appear to cause any DOM updates, only passing them as Handlebars attributes is enough to trigger `didRender`.

I'm not really sure, if this would be considered a bug per se.

**Comment by buschtoens** [comment]
[This Ember Twiddle](https://ember-twiddle.com/6441b12cd72b5726a285622ac08455be?openFiles=components.wrapping-component.js%2Ctemplates.components.inner-component.hbs) demonstrates the issue.

**Comment by alexander-alvarez** [comment]
hmm... I guess we could move https://github.com/alphasights/ember-scrollable/blob/master/addon/components/ember-scrollable.js#L149..L151 to inside of the `ember-scrollbar`, as that mouse offset is only used there.
https://github.com/alphasights/ember-scrollable/search?utf8=%E2%9C%93&q=horizontalMouseOffset&type=

**Comment by buschtoens** [comment]
Sounds good! :+1:
