### ISSUE TITLE
Bump ember-element-resize-detector to fix sendAction deprecation warning

### ISSUE THREAD

**Issue by fran-worley** [alphasights/ember-scrollable#99]
ember-element-resize-detector shipped a fix for this deprecation warning in 0.3.0. Can we bump the dependency version to stop the deprecation warning in our apps?

**Comment by alexander-alvarez** [comment]
Definitely! I'm waiting on https://github.com/alphasights/ember-scrollable/pull/98#issue-226995648 for that as I'm sure a PR is coming after the jquery removal gets merged. Is that okay?

**Comment by Gaurav0** [comment]
This can be closed.
